# Generated by Django 5.1.1 on 2024-09-20 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=200)),
                ('course_duration', models.CharField(max_length=100)),
                ('course_type', models.CharField(max_length=100)),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses_guidance.stream')),
            ],
        ),
    ]
